# Generated by Django 4.2 on 2023-11-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='jobarticle',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='privatearticle',
            options={'ordering': ['created_date']},
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='id',
        ),
        migrations.AddField(
            model_name='articletag',
            name='tag_type',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Job')], default=1),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='tag_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='jobarticle',
            name='job_tag_names',
        ),
        migrations.RemoveField(
            model_name='privatearticle',
            name='private_tag_names',
        ),
        migrations.AddField(
            model_name='jobarticle',
            name='job_tag_names',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='privatearticle',
            name='private_tag_names',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
