name: mypy check

on:
  push:
    branches:
      - main
      # - development
      # - feature/*
      - github_action_test

jobs:
  type-check-only:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # 使用するPythonのバージョンを指定

    - name: Install Poetry
      run: |
        pip install poetry==1.7.1
        export PATH="$HOME/.local/bin:$PATH"
        poetry --version

    - name: Configure Poetry
      run: poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run mypy
      run: mypy blog django_sample  # チェックするディレクトリを指定
